# Generated by Django 3.0.5 on 2021-01-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('nick', models.CharField(max_length=15)),
                ('passwd', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=40)),
                ('llave_privada', models.CharField(max_length=254)),
                ('llave_publica', models.CharField(max_length=254)),
            ],
        ),
    ]
