# Generated by Django 3.0.5 on 2021-01-18 10:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 10, 39, 36, 744537, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='llave_privada',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='registro',
            name='llave_publica',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='registro',
            name='passwd',
            field=models.CharField(max_length=256),
        ),
    ]
